eval "$(starship init zsh)"

source /opt/homebrew/share/zsh-autosuggestions/zsh-autosuggestions.zsh
source /opt/homebrew/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
FPATH=/opt/homebrew/share/zsh-completions:$FPATH
FPATH=/opt/homebrew/share/zsh/site-functions:$FPATH

# is it necessary?
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

#  eval "$(anyenv init -)" # if you use anyenv
# . /opt/homebrew/opt/asdf/libexec/asdf.sh # if you use asdf

