# install depends on which needs
# brew "asdf"
# brew "anyenv"

# brew "openssl@3"
brew "zstd"
brew "fd"
brew "git"
brew "lazygit"
brew "neovim"
brew "ripgrep"
brew "starship"
brew "watchman"
brew "zsh"
brew "zsh-autosuggestions"
brew "zsh-completions"
brew "zsh-syntax-highlighting"

# it maybe unnecessary
# brew "peco"

# private needs
# brew "golang-migrate"
# brew "heroku/brew/heroku"
# brew "postgresql@14"
# brew "mysql", restart_service: :changed
